### ISSUE TITLE
Email verification should require no login

### ISSUE THREAD

**Issue by leesh3288** [nuang-ee/GonPortal#6]
Usually email verification requires no login, and clicking the verification link should suffice. Check if below JWT authentication is needed.

https://github.com/nuang-ee/GonPortal/blob/57c51d0886a811e2e56f30936bb9ceaae691ba55/Server/Controllers/Recruitment/AccountController.ts#L130

**Comment by nuang-ee** [comment]
Seems like I made a mistake there. Thanks for noticing me, resolved this issue in commit [824464b](https://github.com/nuang-ee/GonPortal/commit/824464b13deff411128247116737b3a29755ee89).
